# set up trigger to build after new changes are pushed to master
trigger:
- master

# set up trigger to kick off pr build
pr:
  branches:
    include:
    - master
  autoCancel: true

# set the server to run on
pool:
  vmImage: 'Ubuntu-16.04'

steps:
# install specific version of node
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Install Node.js'

# run build and test
- script: |
    npm install
    npm run build
    npm run test
  displayName: 'npm install, build, and test'
